"""empty message

Revision ID: 141396cd60a5
Revises: 
Create Date: 2018-09-04 11:12:39.269067

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '141396cd60a5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_service',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('s_name', sa.String(length=32), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('s_token', sa.String(length=256), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('robot_id', sa.Integer(), nullable=False),
    sa.Column('state', sa.Enum('在线', '不在线'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('s_name')
    )
    op.drop_index('index_api_key', table_name='user_open_product')
    op.drop_index('index_app_id', table_name='user_open_product')
    op.drop_table('user_open_product')
    op.drop_table('word_frequency')
    op.drop_table('product')
    op.drop_index('ix_user_identity', table_name='user')
    op.drop_index('mobile', table_name='user')
    op.drop_index('name', table_name='user')
    op.drop_table('user')
    op.drop_index('index_api_key', table_name='robot_settings')
    op.drop_index('index_app_id', table_name='robot_settings')
    op.drop_table('robot_settings')
    op.drop_table('qa_settings')
    op.drop_index('ix_data_type_type', table_name='data_type')
    op.drop_table('data_type')
    op.drop_index('ix_chat_logs_is_solve', table_name='admin_chat_logs')
    op.drop_table('admin_chat_logs')
    op.drop_table('blackip_list')
    op.drop_table('data_plan')
    op.drop_index('ix_chat_logs_is_solve', table_name='chat_logs')
    op.drop_index('ix_chat_logs_role', table_name='chat_logs')
    op.drop_table('chat_logs')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_logs',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('role', mysql.ENUM('robot', 'customer'), nullable=False),
    sa.Column('dialog_id', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11, unsigned=True), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('product_id', mysql.INTEGER(display_width=11, unsigned=True), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('content', mysql.TEXT(), nullable=True),
    sa.Column('is_solve', mysql.ENUM('未选', '已解决', '未解决'), nullable=True),
    sa.Column('create_time', mysql.DATETIME(), nullable=True),
    sa.Column('update_time', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_index('ix_chat_logs_role', 'chat_logs', ['role'], unique=False)
    op.create_index('ix_chat_logs_is_solve', 'chat_logs', ['is_solve'], unique=False)
    op.create_table('data_plan',
    sa.Column('create_time', mysql.DATETIME(), nullable=True),
    sa.Column('update_time', mysql.DATETIME(), nullable=True),
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('month_balance', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('month_expiration_time', mysql.DATETIME(), nullable=True),
    sa.Column('month_free', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('year_balance', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('year_expiration_time', mysql.DATETIME(), nullable=True),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_table('blackip_list',
    sa.Column('id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=True, nullable=False),
    sa.Column('ip', mysql.VARCHAR(length=128), server_default=sa.text("''"), nullable=False),
    sa.Column('create_time', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_table('admin_chat_logs',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('dialog_id', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11, unsigned=True), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('product_id', mysql.INTEGER(display_width=11, unsigned=True), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('question', mysql.VARCHAR(length=256), nullable=False),
    sa.Column('answer', mysql.TEXT(), nullable=True),
    sa.Column('is_solve', mysql.ENUM('未选', '已解决', '未解决'), nullable=True),
    sa.Column('create_time', mysql.DATETIME(), nullable=True),
    sa.Column('update_time', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_index('ix_chat_logs_is_solve', 'admin_chat_logs', ['is_solve'], unique=False)
    op.create_table('data_type',
    sa.Column('create_time', mysql.DATETIME(), nullable=True),
    sa.Column('update_time', mysql.DATETIME(), nullable=True),
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('type', mysql.ENUM('年度', '季度', '月度', '自定义'), nullable=True),
    sa.Column('total_num', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('money', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_index('ix_data_type_type', 'data_type', ['type'], unique=False)
    op.create_table('qa_settings',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('question', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('answer', mysql.TEXT(), nullable=False),
    sa.Column('weight', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('product_id', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('user_id', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('create_time', mysql.DATETIME(), nullable=True),
    sa.Column('update_time', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_table('robot_settings',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('product_id', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('welcome_words', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('wait_words', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('timeout_words', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('app_id', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('api_key', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('secret_key', mysql.VARCHAR(length=128), server_default=sa.text("''"), nullable=True),
    sa.Column('robot_name', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('robot_type', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('picture', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('uri', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('create_time', mysql.DATETIME(), nullable=True),
    sa.Column('update_time', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_index('index_app_id', 'robot_settings', ['app_id'], unique=True)
    op.create_index('index_api_key', 'robot_settings', ['api_key'], unique=True)
    op.create_table('user',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('identity', mysql.ENUM('admin', 'custume'), nullable=True),
    sa.Column('company', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('mobile', mysql.VARCHAR(length=11), nullable=False),
    sa.Column('password_hash', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('create_time', mysql.DATETIME(), nullable=True),
    sa.Column('update_time', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_index('name', 'user', ['name'], unique=True)
    op.create_index('mobile', 'user', ['mobile'], unique=True)
    op.create_index('ix_user_identity', 'user', ['identity'], unique=False)
    op.create_table('product',
    sa.Column('id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=True, nullable=False),
    sa.Column('code', mysql.VARCHAR(length=30), server_default=sa.text("''"), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=60), server_default=sa.text("''"), nullable=False),
    sa.Column('display_name', mysql.VARCHAR(length=60), server_default=sa.text("''"), nullable=False),
    sa.Column('url', mysql.VARCHAR(length=120), server_default=sa.text("''"), nullable=False),
    sa.Column('insurance_company', mysql.VARCHAR(length=128), server_default=sa.text("''"), nullable=False),
    sa.Column('insurance_product', mysql.VARCHAR(length=128), server_default=sa.text("''"), nullable=False),
    sa.Column('policy_id', mysql.INTEGER(display_width=11, unsigned=True), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('policy_type', mysql.INTEGER(display_width=11, unsigned=True), server_default=sa.text("'1'"), autoincrement=False, nullable=False),
    sa.Column('create_time', mysql.TIMESTAMP(), nullable=True),
    sa.Column('update_time', mysql.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_comment='机器人产品表',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_table('word_frequency',
    sa.Column('create_time', mysql.DATETIME(), nullable=True),
    sa.Column('update_time', mysql.DATETIME(), nullable=True),
    sa.Column('id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=True, nullable=False),
    sa.Column('word', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('tag', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('counts', mysql.INTEGER(display_width=10), autoincrement=False, nullable=True),
    sa.Column('user_id', mysql.INTEGER(display_width=10, unsigned=True), server_default=sa.text("'1'"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_table('user_open_product',
    sa.Column('id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=10, unsigned=True), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('product_id', mysql.INTEGER(display_width=10, unsigned=True), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('app_id', mysql.VARCHAR(length=30), server_default=sa.text("''"), nullable=False),
    sa.Column('api_key', mysql.VARCHAR(length=120), server_default=sa.text("''"), nullable=False),
    sa.Column('secret_key', mysql.VARCHAR(length=120), server_default=sa.text("''"), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=120), server_default=sa.text("''"), nullable=False),
    sa.Column('intro', mysql.VARCHAR(length=255), server_default=sa.text("''"), nullable=False),
    sa.Column('create_time', mysql.TIMESTAMP(), nullable=True),
    sa.Column('update_time', mysql.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_comment='客户开通的机器人记录表',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB',
    mysql_row_format='COMPACT'
    )
    op.create_index('index_app_id', 'user_open_product', ['app_id'], unique=True)
    op.create_index('index_api_key', 'user_open_product', ['api_key'], unique=True)
    op.drop_table('customer_service')
    # ### end Alembic commands ###
